[tool.poetry]
name = "phl-budget-data"
version = "0.1.3"
description = "PHL Budget Data"
authors = ["Nick Hand <nick.hand@phila.gov>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/PhiladelphiaController/phl-budget-data"
repository = "https://github.com/PhiladelphiaController/phl-budget-data"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
exclude = [ "src/phl_budget_data/data/raw"]

[tool.poetry.dependencies]
python = "^3.7.1"
click = "^7.0"
selenium = "^3.141.0"
numpy = "1.18.0"
pandas = "^1.2.1"
pdfplumber = "^0.5.25"
webdriver-manager = "^3.3.0"
desert = "^2020.11.18"
intervaltree = "^3.1.0"
loguru = "^0.5.3"
python-dotenv = "^0.15.0"
boto3 = "^1.17.12"
beautifulsoup4 = "^4.9.3"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
coverage = {extras = ["toml"], version = "^5.3"}
mypy = "^0.790"
pre-commit = "^2.8.2"
flake8 = "^3.8.4"
black = "^20.8b1"
jupyterlab = "^3.0.5"
matplotlib = "^3.3.4"
jupyterlab_code_formatter = "^1.4.2"
jedi = "0.17.1"
isort = "^5.7.0"
ipympl = "^0.6.3"

[tool.poetry.scripts]
phl-etl-monthly-collections = "phl_budget_data.__main__:monthly_collections_etl"
phl-etl-sector-collections = "phl_budget_data.__main__:etl_sector_collections"
phl-update-monthly-city-collections = "phl_budget_data.etl.sentinel.core:update_monthly_city_collections"
phl-update-monthly-school-collections = "phl_budget_data.etl.sentinel.core:update_monthly_school_collections"
phl-update-monthly-wage-collections = "phl_budget_data.etl.sentinel.core:update_monthly_wage_collections"


[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["phl_budget_data"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
